/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez;

/**
 *
 * @author jorge
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblA1 = new javax.swing.JLabel();
        lblB1 = new javax.swing.JLabel();
        lblC1 = new javax.swing.JLabel();
        lblD1 = new javax.swing.JLabel();
        lblE1 = new javax.swing.JLabel();
        lblF1 = new javax.swing.JLabel();
        lblG1 = new javax.swing.JLabel();
        lblH1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        lblB2 = new javax.swing.JLabel();
        lblC2 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        lblE2 = new javax.swing.JLabel();
        lblF2 = new javax.swing.JLabel();
        lblG2 = new javax.swing.JLabel();
        lblH2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();
        lblB3 = new javax.swing.JLabel();
        lblC3 = new javax.swing.JLabel();
        lblD3 = new javax.swing.JLabel();
        lblE3 = new javax.swing.JLabel();
        lblF3 = new javax.swing.JLabel();
        lblG3 = new javax.swing.JLabel();
        lblH3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblA4 = new javax.swing.JLabel();
        lblB4 = new javax.swing.JLabel();
        lblC4 = new javax.swing.JLabel();
        lblD4 = new javax.swing.JLabel();
        lblE4 = new javax.swing.JLabel();
        lblF4 = new javax.swing.JLabel();
        lblG4 = new javax.swing.JLabel();
        lblH4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblA5 = new javax.swing.JLabel();
        lblB5 = new javax.swing.JLabel();
        lblC5 = new javax.swing.JLabel();
        lblD5 = new javax.swing.JLabel();
        lblE5 = new javax.swing.JLabel();
        lblF5 = new javax.swing.JLabel();
        lblG5 = new javax.swing.JLabel();
        lblH5 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lblA6 = new javax.swing.JLabel();
        lblB6 = new javax.swing.JLabel();
        lblC6 = new javax.swing.JLabel();
        lblD6 = new javax.swing.JLabel();
        lblE6 = new javax.swing.JLabel();
        lblF6 = new javax.swing.JLabel();
        lblG6 = new javax.swing.JLabel();
        lblH6 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblA7 = new javax.swing.JLabel();
        lblB7 = new javax.swing.JLabel();
        lblC7 = new javax.swing.JLabel();
        lblD7 = new javax.swing.JLabel();
        lblE7 = new javax.swing.JLabel();
        lblF7 = new javax.swing.JLabel();
        lblG7 = new javax.swing.JLabel();
        lblH7 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblA8 = new javax.swing.JLabel();
        lblB8 = new javax.swing.JLabel();
        lblC8 = new javax.swing.JLabel();
        lblD8 = new javax.swing.JLabel();
        lblE8 = new javax.swing.JLabel();
        lblF8 = new javax.swing.JLabel();
        lblG8 = new javax.swing.JLabel();
        lblH8 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajedrez");
        setPreferredSize(new java.awt.Dimension(630, 630));

        jPanel1.setLayout(new java.awt.GridLayout(10, 10));
        jPanel1.add(jLabel18);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("A");
        jPanel1.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("B");
        jPanel1.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("C");
        jPanel1.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("D");
        jPanel1.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("E");
        jPanel1.add(jLabel5);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("F");
        jPanel1.add(jLabel8);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("G");
        jPanel1.add(jLabel7);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("H");
        jPanel1.add(jLabel6);
        jPanel1.add(jLabel9);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("1");
        jPanel1.add(jLabel21);

        lblA1.setBackground(new java.awt.Color(51, 153, 0));
        lblA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_rook.png"))); // NOI18N
        lblA1.setOpaque(true);
        jPanel1.add(lblA1);

        lblB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_knight.png"))); // NOI18N
        jPanel1.add(lblB1);

        lblC1.setBackground(new java.awt.Color(51, 153, 0));
        lblC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_bishop.png"))); // NOI18N
        lblC1.setOpaque(true);
        jPanel1.add(lblC1);

        lblD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_king.png"))); // NOI18N
        jPanel1.add(lblD1);

        lblE1.setBackground(new java.awt.Color(51, 153, 0));
        lblE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_queen.png"))); // NOI18N
        lblE1.setOpaque(true);
        jPanel1.add(lblE1);

        lblF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_bishop.png"))); // NOI18N
        jPanel1.add(lblF1);

        lblG1.setBackground(new java.awt.Color(51, 153, 0));
        lblG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_knight.png"))); // NOI18N
        lblG1.setOpaque(true);
        jPanel1.add(lblG1);

        lblH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        jPanel1.add(lblH1);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("1");
        jPanel1.add(jLabel22);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("2");
        jPanel1.add(jLabel23);

        lblA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        jPanel1.add(lblA2);

        lblB2.setBackground(new java.awt.Color(51, 153, 0));
        lblB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        lblB2.setOpaque(true);
        jPanel1.add(lblB2);
        lblB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N

        lblC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        jPanel1.add(lblC2);

        lblD2.setBackground(new java.awt.Color(51, 153, 0));
        lblD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        lblD2.setOpaque(true);
        jPanel1.add(lblD2);

        lblE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        jPanel1.add(lblE2);

        lblF2.setBackground(new java.awt.Color(51, 153, 0));
        lblF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        lblF2.setOpaque(true);
        jPanel1.add(lblF2);

        lblG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        jPanel1.add(lblG2);

        lblH2.setBackground(new java.awt.Color(51, 153, 0));
        lblH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/black_pawn.png"))); // NOI18N
        lblH2.setOpaque(true);
        jPanel1.add(lblH2);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("2");
        jPanel1.add(jLabel24);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("3");
        jPanel1.add(jLabel25);

        lblA3.setBackground(new java.awt.Color(51, 153, 0));
        lblA3.setOpaque(true);
        jPanel1.add(lblA3);
        jPanel1.add(lblB3);

        lblC3.setBackground(new java.awt.Color(51, 153, 0));
        lblC3.setOpaque(true);
        jPanel1.add(lblC3);
        jPanel1.add(lblD3);

        lblE3.setBackground(new java.awt.Color(51, 153, 0));
        lblE3.setOpaque(true);
        jPanel1.add(lblE3);
        jPanel1.add(lblF3);

        lblG3.setBackground(new java.awt.Color(51, 153, 0));
        lblG3.setOpaque(true);
        jPanel1.add(lblG3);
        jPanel1.add(lblH3);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("3");
        jPanel1.add(jLabel26);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("4");
        jPanel1.add(jLabel28);
        jPanel1.add(lblA4);

        lblB4.setBackground(new java.awt.Color(51, 153, 0));
        lblB4.setOpaque(true);
        jPanel1.add(lblB4);
        jPanel1.add(lblC4);

        lblD4.setBackground(new java.awt.Color(51, 153, 0));
        lblD4.setOpaque(true);
        jPanel1.add(lblD4);
        jPanel1.add(lblE4);

        lblF4.setBackground(new java.awt.Color(51, 153, 0));
        lblF4.setOpaque(true);
        jPanel1.add(lblF4);
        jPanel1.add(lblG4);

        lblH4.setBackground(new java.awt.Color(51, 153, 0));
        lblH4.setOpaque(true);
        jPanel1.add(lblH4);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("4");
        jPanel1.add(jLabel29);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("5");
        jPanel1.add(jLabel27);

        lblA5.setBackground(new java.awt.Color(51, 153, 0));
        lblA5.setOpaque(true);
        jPanel1.add(lblA5);
        jPanel1.add(lblB5);

        lblC5.setBackground(new java.awt.Color(51, 153, 0));
        lblC5.setOpaque(true);
        jPanel1.add(lblC5);
        jPanel1.add(lblD5);

        lblE5.setBackground(new java.awt.Color(51, 153, 0));
        lblE5.setOpaque(true);
        jPanel1.add(lblE5);
        jPanel1.add(lblF5);

        lblG5.setBackground(new java.awt.Color(51, 153, 0));
        lblG5.setOpaque(true);
        jPanel1.add(lblG5);
        jPanel1.add(lblH5);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("5");
        jPanel1.add(jLabel34);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("6");
        jPanel1.add(jLabel35);
        jPanel1.add(lblA6);

        lblB6.setBackground(new java.awt.Color(51, 153, 0));
        lblB6.setOpaque(true);
        jPanel1.add(lblB6);
        jPanel1.add(lblC6);

        lblD6.setBackground(new java.awt.Color(51, 153, 0));
        lblD6.setOpaque(true);
        jPanel1.add(lblD6);
        jPanel1.add(lblE6);

        lblF6.setBackground(new java.awt.Color(51, 153, 0));
        lblF6.setOpaque(true);
        jPanel1.add(lblF6);
        jPanel1.add(lblG6);

        lblH6.setBackground(new java.awt.Color(51, 153, 0));
        lblH6.setOpaque(true);
        jPanel1.add(lblH6);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("6");
        jPanel1.add(jLabel33);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("7");
        jPanel1.add(jLabel32);

        lblA7.setBackground(new java.awt.Color(51, 153, 0));
        lblA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_pawn.png"))); // NOI18N
        lblA7.setOpaque(true);
        jPanel1.add(lblA7);

        lblB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_pawn.png"))); // NOI18N
        jPanel1.add(lblB7);

        lblC7.setBackground(new java.awt.Color(51, 153, 0));
        lblC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_pawn.png"))); // NOI18N
        lblC7.setOpaque(true);
        jPanel1.add(lblC7);

        lblD7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_pawn.png"))); // NOI18N
        jPanel1.add(lblD7);

        lblE7.setBackground(new java.awt.Color(51, 153, 0));
        lblE7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_pawn.png"))); // NOI18N
        lblE7.setOpaque(true);
        jPanel1.add(lblE7);

        lblF7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_pawn.png"))); // NOI18N
        jPanel1.add(lblF7);

        lblG7.setBackground(new java.awt.Color(51, 153, 0));
        lblG7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_pawn.png"))); // NOI18N
        lblG7.setOpaque(true);
        jPanel1.add(lblG7);

        lblH7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_pawn.png"))); // NOI18N
        jPanel1.add(lblH7);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("7");
        jPanel1.add(jLabel31);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("8");
        jPanel1.add(jLabel30);

        lblA8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_rook.png"))); // NOI18N
        jPanel1.add(lblA8);

        lblB8.setBackground(new java.awt.Color(51, 153, 0));
        lblB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_knight.png"))); // NOI18N
        lblB8.setOpaque(true);
        jPanel1.add(lblB8);

        lblC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_bishop.png"))); // NOI18N
        jPanel1.add(lblC8);

        lblD8.setBackground(new java.awt.Color(51, 153, 0));
        lblD8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_king.png"))); // NOI18N
        lblD8.setOpaque(true);
        jPanel1.add(lblD8);

        lblE8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_queen.png"))); // NOI18N
        jPanel1.add(lblE8);

        lblF8.setBackground(new java.awt.Color(51, 153, 0));
        lblF8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_bishop.png"))); // NOI18N
        lblF8.setOpaque(true);
        jPanel1.add(lblF8);

        lblG8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_knight.png"))); // NOI18N
        jPanel1.add(lblG8);

        lblH8.setBackground(new java.awt.Color(51, 153, 0));
        lblH8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_rook.png"))); // NOI18N
        lblH8.setOpaque(true);
        jPanel1.add(lblH8);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("8");
        jPanel1.add(jLabel36);
        jPanel1.add(jLabel20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A");
        jPanel1.add(jLabel10);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("B");
        jPanel1.add(jLabel11);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("C");
        jPanel1.add(jLabel12);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("D");
        jPanel1.add(jLabel13);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("E");
        jPanel1.add(jLabel14);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("F");
        jPanel1.add(jLabel15);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("G");
        jPanel1.add(jLabel16);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("H");
        jPanel1.add(jLabel17);
        jPanel1.add(jLabel19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblA4;
    private javax.swing.JLabel lblA5;
    private javax.swing.JLabel lblA6;
    private javax.swing.JLabel lblA7;
    private javax.swing.JLabel lblA8;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblB3;
    private javax.swing.JLabel lblB4;
    private javax.swing.JLabel lblB5;
    private javax.swing.JLabel lblB6;
    private javax.swing.JLabel lblB7;
    private javax.swing.JLabel lblB8;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC5;
    private javax.swing.JLabel lblC6;
    private javax.swing.JLabel lblC7;
    private javax.swing.JLabel lblC8;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD3;
    private javax.swing.JLabel lblD4;
    private javax.swing.JLabel lblD5;
    private javax.swing.JLabel lblD6;
    private javax.swing.JLabel lblD7;
    private javax.swing.JLabel lblD8;
    private javax.swing.JLabel lblE1;
    private javax.swing.JLabel lblE2;
    private javax.swing.JLabel lblE3;
    private javax.swing.JLabel lblE4;
    private javax.swing.JLabel lblE5;
    private javax.swing.JLabel lblE6;
    private javax.swing.JLabel lblE7;
    private javax.swing.JLabel lblE8;
    private javax.swing.JLabel lblF1;
    private javax.swing.JLabel lblF2;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblF6;
    private javax.swing.JLabel lblF7;
    private javax.swing.JLabel lblF8;
    private javax.swing.JLabel lblG1;
    private javax.swing.JLabel lblG2;
    private javax.swing.JLabel lblG3;
    private javax.swing.JLabel lblG4;
    private javax.swing.JLabel lblG5;
    private javax.swing.JLabel lblG6;
    private javax.swing.JLabel lblG7;
    private javax.swing.JLabel lblG8;
    private javax.swing.JLabel lblH1;
    private javax.swing.JLabel lblH2;
    private javax.swing.JLabel lblH3;
    private javax.swing.JLabel lblH4;
    private javax.swing.JLabel lblH5;
    private javax.swing.JLabel lblH6;
    private javax.swing.JLabel lblH7;
    private javax.swing.JLabel lblH8;
    // End of variables declaration//GEN-END:variables
}
